### ISSUE TITLE
does not appear to work with current Todoist api

### ISSUE THREAD

**Issue by tconroy** [davidtaboas/Alfred-Todoist#1]
Hey, I've tried both the public and private client key, as well as the "test token", but nothing seems to actually add the task to the inbox list. Any updates? Am I just doing something wrong?

**Comment by davidtaboas** [comment]
Sorry @tconroy, these days I was a little busy. I've tested the script and it seems still working. 

Can you do reproduce here the error, step by step? With screenshots or writing.

**Comment by tconroy** [comment]
@davidtaboas hm. What do I use as the "token"? 

These are the steps I took to setup:
1. installed your workflow.
2. went to developer.todoist.com, created a new App
3. copied the value under "Test Token" on the app page
4. pasted it into the workflow `token="my test token"` 
5. Tried the workflow in alfred: `todo test task name`

I get the growl notification that a task was added, however if I open my Todoist.app, the task does not show up in the application.

I have tried the Client ID and Client Secret as well (instead of test token), and they do not work either.

**Comment by davidtaboas** [comment]
@tconroy In Todoist, inside Preferences, click on tab "Account". You can find your API token here for use without to be a developer or create an App.

![captura_de_pantalla_2015-11-06_a_las_20_31_36](https://cloud.githubusercontent.com/assets/725182/11006811/30799a5c-84c6-11e5-8b51-fb933571e5ac.png)

**Comment by tconroy** [comment]
ah! it works! I wasn't aware of API Token inside of Todoist, I thought I needed to do it through the developer api. My mistake. :) Would be good to add that image to the readme.

Thanks!
